import type { AgentScanResult } from './scan-agent.ts'

export function generateJudgeReport(r: AgentScanResult): string {
  const lines = [
    '# DepthGuard — Executive Threat Report',
    '',
    `**Package:** ${r.pkg} (${r.ecosystem})`,
    `**Generated:** ${new Date().toISOString()}`,
    `**Why-Now Score:** ${r.whyNow.score}/100`,
    `**Track:** Security & Compliance — Web Data UNLOCKED Hackathon`,
    '',
    '---',
    '',
    '## Verdict',
    r.whyNow.reason,
    '',
    '## Intelligence Gap (OSV vs Bright Data SERP)',
    r.whyNow.gap,
    '',
    `| Metric | Count |`,
    `|--------|-------|`,
    `| Structured threats (OSV/GitHub) | ${r.threats.filter((t) => !t.earlyWarning).length} |`,
    `| Early warnings (SERP-only) | ${r.earlyWarningCount} |`,
    `| Bright Data SERP signals | ${r.webSignals.length} |`,
    `| SERP queries run | ${r.serpStats?.queriesRun ?? '—'} |`,
    `| AI/ML API agents | 3 (brief, why-now, classify) |`,
    '',
    '## AI Executive Brief',
    r.agentBrief,
    '',
    '## Remediation Plan',
    ...r.remediationPlan.map((step, i) => `${i + 1}. ${step}`),
    '',
    '## Bright Data SERP Evidence (live URLs)',
    ...r.webSignals.slice(0, 12).map((s, i) => `${i + 1}. [${s.title}](${s.url})${s.aiVerdict ? ` — AI: ${s.aiVerdict} (${s.aiRelevance}/100)` : ''}`),
    '',
    '## Agent Swarm',
    ...((r.agents ?? []).map((a) => `- **${a.name}**: ${a.status} — ${a.role}`)),
    '',
    '## Bright Data Products',
    r.brightDataProducts.join(', '),
    '',
    '---',
    '*DepthGuard — Autonomous Supply Chain Threat Agent*',
  ]
  return lines.join('\n')
}
